### ISSUE TITLE
Figure out how to chain PRs

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#10]
This will become a necessity soon.
e.g. I want to continue the work I started with #9, but keep the code review nice and short.

I poked around a bit.
- https://github.com/isaacs/github/issues/1500
- https://www.reddit.com/r/github/comments/djdmbj/github_pull_request_dependency

And it seems this is likely a decent solution:
https://probot.github.io/apps/dep

Thoughts @Qwlouse ?

**Comment by taiya** [comment]
this seems interesting reading too:
https://unhashable.com/stacked-pull-requests-keeping-github-diffs-small/

**Comment by vadimkantorov** [comment]
PyTorch uses https://github.com/ezyang/ghstack for that end
