### ISSUE TITLE
Executing from native "bpy" package

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#100]
You can also install Kubric directly on your host system (virtualenv). To achieve this, you need to first manually install `bpy` and the other dependencies. Be warned though: this process can be *very* difficult and frustrating.

First clone the [Kubric git repository](https://github.com/google-research/kubric):
```
git clone https://github.com/google-research/kubric.git
```

Then use ``pip`` to install the non-``bpy`` dependencies:
```
pip install -r requirements.txt
```

⚠️ This step may require installing additional (non-Python) packages; on Ubuntu, for example, the `OpenEXR` Python package depends on `libopenexr-dev`.

Next, install the Blender python module `bpy`. We recommend to first try using the [blenderpy](https://github.com/TylerGubala/blenderpy) project, which aims to make `bpy` pip-installable, and already works for most environments. Note however, that this still requires installing the minimum build dependencies for Blender. Just follow the [install instructions for blenderpy](https://github.com/TylerGubala/blenderpy#getting-started) and make sure to install the correct version of Blender (currently 2.91).

If this approach fails, you can try to manually [build Blender as a Python module](https://wiki.blender.org/wiki/Building_Blender/Other/BlenderAsPyModule). Though be warned, that
⚠️ The option to build Blender as a Python module is not officially supported [...]

Finally, install Kubric using pip from the source directory:
```
pip install .
```

Kubric worker files can then be run normally using python:
```
python examples/helloworld.py
```

**Comment by basilevh** [comment]
What to do about the fact that bpy requires Python 3.7 while kubric requires Python 3.9?

**Comment by taiya** [comment]
Google uses a very specific version of python on the internal codebase.
Kubric is imported inside of google 1-1, so we need to respect that version.

Sadly Kubric cannot mandate the python version affecting 100k+ employees :)

**Comment by taiya** [comment]
@Qwlouse I just checked and it seems we are on 3.7 – should we change Kubric to use that version everywhere?
Indeed it's odd what @basilevh mentions that we have two different versions declared.
