### ISSUE TITLE
Additional render passes error (blender 2.83.2)

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#12]
Commented these out
```
    # bpy.context.scene.use_pass_crypto_object = True  # segmentation
    # bpy.context.scene.pass_crypto_depth = 4
```

Why?
```
Traceback (most recent call last):
  File "/home/atagliasacchi_google_com/dev/kubric/worker.py", line 67, in <module>
    renderer = THREE.Renderer()
  File "./kubric/viewer/blender.py", line 316, in __init__
    bpy.context.scene.use_pass_crypto_object = True  # segmentation
AttributeError: 'Scene' object has no attribute 'use_pass_crypto_object'
```

**Comment by taiya** [comment]
Can you add a comment on how it was resolved?
I don't see a commit attached to this.

**Comment by Qwlouse** [comment]
These properties should be set on the view-layer and not on the scene. (This was output incorrectly by the Blender python-info)
The relevant changed lines are here (only 359, 364, and 365 matter for this but I also refactored the others):

https://github.com/google-research/kubric/blob/a6cb80f20abed2261bb45b34ceba5c46533a7698/kubric/viewer/blender.py#L359-L365
