### ISSUE TITLE
How to deal with sub-optimal (Cycles) rendering quality of GLTF assets?

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#129]
Some problematic models:
– Police car: 02958343/114b662c64caba81bb07f8c2248e54bc
– Police car2: 02958343/8577f3f82d5ce3ecc2fe329dd557eb52
– Rifle: 04090263/18807814a9cefedcd957eaf7f4edb205 

Also referenced here:
https://github.com/ShapeNet/shapenet-viewer/issues/28

Potential solutions:
1. massive pre-processing of shapenet (out of scope)
2. shape-offset trick (by @Qwlouse)
3. automatic detection of rendering problems (OpenGL ≠ PBR → unfeasible)
4. keep a list of "bad" models and update it over time?

**Comment by taiya** [comment]
@Qwlouse maybe you can quickly document what is the gist of the solution here?

**Comment by Qwlouse** [comment]
Models look pretty good after taking the following steps:
  * convert to gltf then import into blender
  * disable auto-smoothing
  * split edges with an angle above 70 degrees (Split Edge modifier)
  * move every face an epsilon in the direction of its normal to reduce / eliminate clipping artifacts (Displace modifier with tiny strength, e.g. 1e-5)

For example the police car (`02958343/114b662c64caba81bb07f8c2248e54bc`) looks like this before:

![police_car_114b662c64caba81bb07f8c2248e54bc_gltf](https://user-images.githubusercontent.com/1160920/130111223-82ea5f94-4db1-4136-8e13-83bd356ea513.png)

And like this after:
![police_car_114b662c64caba81bb07f8c2248e54bc_final](https://user-images.githubusercontent.com/1160920/130111253-dbf16d0e-c342-4aee-826b-01a2f333b6c7.png)

Cleanup script is [here](https://github.com/google-research/kubric/blob/issue33/shapenet2kubric/bpy_clean_mesh.py) (assumes gltf model).

**Comment by CodeLHY** [comment]
> Models look pretty good after taking the following steps:
> 
> * convert to gltf then import into blender
> * disable auto-smoothing
> * split edges with an angle above 70 degrees (Split Edge modifier)
> * move every face an epsilon in the direction of its normal to reduce / eliminate clipping artifacts (Displace modifier with tiny strength, e.g. 1e-5)
> 
> For example the police car (`02958343/114b662c64caba81bb07f8c2248e54bc`) looks like this before:
> 
> ![police_car_114b662c64caba81bb07f8c2248e54bc_gltf](https://user-images.githubusercontent.com/1160920/130111223-82ea5f94-4db1-4136-8e13-83bd356ea513.png)
> 
> And like this after: ![police_car_114b662c64caba81bb07f8c2248e54bc_final](https://user-images.githubusercontent.com/1160920/130111253-dbf16d0e-c342-4aee-826b-01a2f333b6c7.png)
> 
> Cleanup script is [here](https://github.com/google-research/kubric/blob/issue33/shapenet2kubric/bpy_clean_mesh.py) (assumes gltf model).

Hi, when I click in to the link you have mentioned I get a 404 error, could you please update the link?

**Comment by CodeLHY** [comment]
I tried to use this script to clean the model of  03642806/e466c2c86a439c1faebff3b001eb4a27, but it seems looks bad, do you have any advice? 
![image](https://user-images.githubusercontent.com/39873455/161500929-c6b6ba54-801e-47e0-bb37-bd23ff6ca43b.png)

**Comment by taiya** [comment]
@CodeLHY out solution has been to add them to a [denylist](https://github.com/google-research/kubric/blob/main/shapenet2kubric/shapenet_denylist.py)
We have ~dozen models where the pain to fix the rendering is just not worth the effort.

**Comment by MrXandbadas** [comment]
I know this is closed, But could the Kubric pipeline be used to fabricate similar issues in working models with their full "fixed" version as a output? Somewhat similar to the Singular View Reconstruction Challenge?

**Comment by taiya** [comment]
I am not sure what the question is, so unable to reply.

**Comment by MrXandbadas** [comment]
Passing thoughts on repairing the deny list
[2020 Paper on Model Repair with Quality-Based Reinforcement Learning ](http://www.jot.fm/issues/issue_2020_02/article17.pdf)
My brain is not cobbling the English together well but I've been contemplating this for weeks now. I'll give it another try xD

In essence I'm wondering if it is worth the effort to implement a tool that takes a broken model from the deny list and returns a fixed model to use in its place.
If we need data to fine-tune the tool (or Neural Network) in question then we can look no further than the kubric pipeline and the examples exported through this thread. By breaking the models that currently don't need a fix up we can create the required dataset of broken to repaired models.

**Comment by taiya** [comment]
It's a question of whether ~100 / 50.000 is that meaningful to fix.
If I were to attempt to fix these, I'd likely train a differentiable rendering pipeline that takes the OpenGL rendered views (+known illumination settings) and generates a watertight textured model via optimization (see a recent paper from NVIDIA in regards).

IMHO: not worth the time
