### ISSUE TITLE
[bpy] Properly importing OBJs from file

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#14]
In `blender.Scene.add_from_file()`

This operation
`bpy.ops.import_scene.obj(filepath=path, axis_forward='Y', axis_up='Z')`

Does not update the `bpy.context.object` (to create blender.Object3D)

So I resorted to `bpy.context.selected_objects[:]` as mentioned [here](https://blender.stackexchange.com/questions/24133/modify-obj-after-import-using-python) 

But this solution needs to be certified.

**Comment by Qwlouse** [comment]
This is not a problem and should behave as intended.
 `bpy.context.object` only stores the currently active object, which is different from the list of currently selected objects `bpy.context.selected_objects`.
See [the documentation](https://docs.blender.org/manual/en/latest/scene_layout/object/selecting.html) and [this question](https://blender.stackexchange.com/questions/27396/whats-the-difference-among-object-active-object-and-selected-objects).

**Comment by taiya** [comment]
Yes, the implied assumption is that importing a new object selects it.
We should add unit tests to ensure this behavior will persist.
