### ISSUE TITLE
Depth vs Z

### ISSUE THREAD

**Issue by Qwlouse** [google-research/kubric#151]
We would like to export depth, but the value exported by blender for each pixel is not actually the depth (i.e. distance from the camera), but instead a Z value (i.e. distance from the plane orthogonal to the camera direction).
We should correct this and export depth rather than this Z value. The math for the correction is not hard.

**Comment by ZhiangChen** [comment]
actually, in many computer vision applications,  the depth images are distance along the camera z axis. please provide an option for z-axis depth rendering.
