### ISSUE TITLE
why logging of flags is reported as error on GCP?

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#162]
```
def log_my_flags(flags):
  flags_string = pprint.pformat(vars(flags), indent=2, width=100)
  logger.info(flags_string)
```

![image](https://user-images.githubusercontent.com/4480573/139618513-d5a25940-2aa2-4498-9f4b-8fb1e11246ce.png)

**Comment by Qwlouse** [comment]
Not sure. I was also confused by this. My guess is that it has to do with multi-line logging messages.

**Comment by taiya** [comment]
Obsolete, as you are officially moving to a Beam pipeline
