### ISSUE TITLE
Unable to access gs://kubric-public

### ISSUE THREAD

**Issue by wilson1yan** [google-research/kubric#180]
Hi,

I'm interested in using some of the datasets presented in [SAVi](https://slot-attention-video.github.io/). However, I'm unable to access and download any data from gs://kubric-public (in particular HDRI backgrounds + GSO objects for MOVi++), getting the error:

> ServiceException: 401 Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.

 Is it intended to be access restricted, as things are still in development?

I think I can download the GSO objects myself, but not sure which backgrounds to select for hdrihaven. Any help would be appreciated!

**Comment by wilson1yan** [comment]
After some more looking around, it looks like I can generate the GSO files myself using `kubric/scripts/download_GSO.py`.

For the HDR backgrounds, I can just download some myself, but the code [here](https://github.com/google-research/kubric/blob/12d5aa4297e3de9cbfbb7bf9978366efe191e369/kubric/assets/utils.py#L98) seems to fetch some `dome.blend` file which I'm unable to find.

**Comment by wilson1yan** [comment]
Using data output from `kubric/scripts/download_GSO.py` works for me, but [a few lines](https://github.com/google-research/kubric/blob/12d5aa4297e3de9cbfbb7bf9978366efe191e369/examples/movid.py#L265) in `examples/movid.py` error for me when looking for a `category_id` that does not seem to exist. I don't need that info so just commenting those lines out / replacing `category` with some dummy value resolved the issue for me.

**Comment by Markus28** [comment]
I am having a similar problem. Are there plans to fix this or is using `kubric/scripts/download_GSO.py` (which seems to have a few bugs itself, I believe) the only option?

**Comment by Qwlouse** [comment]
This should all be resolved by now: 
* [gs://kubric-public](https://pantheon.corp.google.com/storage/browser/kubric-public) is actually public now and contains the preprocessed GSO and HDRI assets. 
* The movid script has been refactored and split up and current versions can be found under [challenges/movi](https://github.com/google-research/kubric/tree/main/challenges/movi)
* many  of the datasets are also up, and the rest should become available very soon.

**Comment by wilson1yan** [comment]
Thanks!
