### ISSUE TITLE
Is there any example of loading objects in the scene?

### ISSUE THREAD

**Issue by Steve-Tod** [google-research/kubric#185]
Hi,

Thank you for your great work! It must take a great amount of effort to implement such a system!

Current only APIs for loading simple primitives and ShapeNet shapes are presented in the examples. Is there any simple way to load our own objects (maybe in the form of an obj file)?

**Comment by Steve-Tod** [comment]
For example, how should I pre-process and load google scanned objects for simulation and rendering?

**Comment by Qwlouse** [comment]
Hi,
thank you for your question and sorry for being so unresponsive.

Two part answer:

Firstly, for ShapeNet and Google Scanned Objects there should be very little work on your part required. 
For example this should work for GSO: 
``` python
import kubric as kb
...
gso = kb.AssetSource.from_manifest("gs://kubric-public/assets/GSO/GSO.json")
obj = gso.create(asset_id="Marvel_Avengers_Titan_Hero_Series_Doctor_Doom")
scene += obj
```
See the [movi_c_worker](https://github.com/google-research/kubric/blob/9dd4ed18e27eadac3a28c9f6b2ae3e273b707aaf/challenges/movi/movi_c_worker.py) for a full example.

The same works for ShapeNet with the only exception that you first need to register at the [shapenet.org](https://shapenet.org/) and agree to their terms, to find the corresponding AssetSource link. See [shapenet.py](https://github.com/google-research/kubric/blob/9dd4ed18e27eadac3a28c9f6b2ae3e273b707aaf/examples/shapenet.py) for a full example.


The second part about preprocessing custom objects is slightly more complicated. We do not yet have documentation on that. 
If you just want to add a single asset in `obj`, `gltf` or `blender` format for rendering, then the easiest would probably be to manually instantiate a `FileBasedObject`. Something like this:

```python
obj = kb.FileBasedObject(
  asset_id="custom", 
  render_filename="custom.obj", 
  bounds=((-1, -1, -1), (1, 1, 1)),
  simulation_filename=None)

scene += obj
```
To make this work for simulation you would need to create a collision mesh in `obj` format and a corresponding `urdf` file that you can pass as `simulation_filename`. If your mesh is watertight, you can take a look at the [GSO preprocessing script](https://github.com/google-research/kubric/blob/9dd4ed18e27eadac3a28c9f6b2ae3e273b707aaf/kubric/scripts/download_GSO.py) about how to do that. If not, then things get complicated, and you will have to do more than that. The [ShapeNet preprocessing scripts](https://github.com/google-research/kubric/blob/9dd4ed18e27eadac3a28c9f6b2ae3e273b707aaf/shapenet2kubric/convert.py#L88) can serve as a starting point there.

**Comment by Steve-Tod** [comment]
Thank you! Do we need to manually download google scanned objects and put them in a certain directory?

**Comment by Steve-Tod** [comment]
Thank you for your help!

**Comment by WenyuanQ** [comment]
> 

Hi Thank you very much for the helping!

I have successfully added '.obj' file into scene using function: kb.FileBasedObject(). I'd like to ask if I can add '.mtl' or '.jpg' texture information into  this object? Thanks.
And another question, when I add object into scene, seems it cannot generate segmentation annotation. Could you please tell me how can I make it correct?
