### ISSUE TITLE
Explore MeshCat as a WebGL backend

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#2]
https://github.com/rdeits/meshcat-python

**Comment by Qwlouse** [comment]
I think [pythreejs](https://pythreejs.readthedocs.io/en/stable/) might be a better fit. It seems to be more mature and doesn't require starting a separate server.

**Comment by taiya** [comment]
1) AFAIK, the server can be started within the same Jupyter
2) @peteflorence was mentioning MeshCat is built on-top of threejs, so it's possible they are API-compatible?
