### ISSUE TITLE
How to import Kubric packages into blender

### ISSUE THREAD

**Issue by Karthus0930** [google-research/kubric#214]
Hi,I input the code in the paper into blender. It is found that there is no package imported into Kubric. How can Kubric be imported into blender to run code? Is it related to Blender's version?

**Comment by taiya** [comment]
That's not how this work, we don't integrate kubric into blender.
We do the opposite, we integrate blender into pure python.

As per README.md, this is how you use it:
```
git clone https://github.com/google-research/kubric.git
cd kubric
docker pull kubricdockerhub/kubruntu
docker run --rm --interactive \
           --user $(id -u):$(id -g) \
           --volume "$(pwd):/kubric" \
           kubricdockerhub/kubruntu \
           /usr/bin/python3 examples/helloworld.py
 ```
