### ISSUE TITLE
World coordinate frame

### ISSUE THREAD

**Issue by hwjiang1510** [google-research/kubric#215]
Thanks for the great work!

I am wondering what is the setting of the world coordinate frame in Kubric.
As I found [here](https://github.com/google-research/kubric/blob/4ac1eab0cafe531141ab21c34052b163221c5ef0/kubric/core/objects.py#L76), is the world frame of Kubric has **X-right, Y-point-inside-screen, Z-up**?

**Comment by Qwlouse** [comment]
Yes, that is indeed the default world-coordinate frame in Blender / Kubric.
