### ISSUE TITLE
Update non-docker installation guide

### ISSUE THREAD

**Issue by basilevh** [google-research/kubric#229]
The guide [Executing from native "bpy" package](https://github.com/google-research/kubric/issues/100) is a bit outdated because Kubric has since [upgraded to Blender 2.93](https://github.com/google-research/kubric/issues/115). I am only able to install bpy for version 2.91 via the [linked blenderpy instructions](https://github.com/TylerGubala/blenderpy#getting-started), but the current Kubric release is not compatible with that. Perhaps I could use an old version of kubric (for example 0.1.1 which is on pypi), but given the freshness of the framework I would prefer to stick to recent code. At the same time, I would like to run the kubric data generation pipeline within my own environment/framework, i.e. outside of docker. So I guess my question is, are there any plans to update the aforementioned guide and/or to support this kind of workflow at all? Thanks!

**Comment by taiya** [comment]
Feel free to send a PR with an update to documentation, as the only fully
supported way of executing Kubric is via docker at the moment.

There was way too much pain for the average user in setting up python packages.
