### ISSUE TITLE
pybullet.error: Not connected to physics server.

### ISSUE THREAD

**Issue by HAWLYQ** [google-research/kubric#234]
Hi, I am using Kubric to construct a dataset. When I tried to iteratively construct **multiple** scenes, I got **pybullet.error: Not connected to physics server**.  The error was sometimes returned at "kubric/simulator/pybullet.py", line 239, in run
    pb.stepSimulation() and sometimes returned at "kubric/simulator/pybullet.py", line 312, in set_quaternion
    position, _ = pb.getBasePositionAndOrientation(object_idx).

 For example, just add a for loop in the example/simulate.py as follows:

    import logging
    import numpy as np
    import kubric as kb
    from kubric.renderer.blender import Blender as KubricBlender
    from kubric.simulator.pybullet import PyBullet as KubricSimulator
    
    logging.basicConfig(level="INFO")  # < CRITICAL, ERROR, WARNING, INFO, DEBUG
    from tqdm import tqdm

    for i in tqdm(range(10)):

        # --- create scene and attach a renderer and simulator
        scene = kb.Scene(resolution=(256, 256))
        scene.frame_end = 10   # < numbers of frames to render
        scene.frame_rate = 24  # < rendering framerate
        scene.step_rate = 240  # < simulation framerate
        renderer = KubricBlender(scene)
        simulator = KubricSimulator(scene)
    
        # --- populate the scene with objects, lights, cameras
        scene += kb.Cube(name="floor", scale=(3, 3, 0.1), position=(0, 0, -0.1),
                        static=True)
        scene += kb.DirectionalLight(name="sun", position=(-1, -0.5, 3),
                                    look_at=(0, 0, 0), intensity=1.5)
        scene.camera = kb.PerspectiveCamera(name="camera", position=(2, -0.5, 4),
                                            look_at=(0, 0, 0))
        # --- generates spheres randomly within a spawn region
        spawn_region = [[-1, -1, 0], [1, 1, 1]]
        rng = np.random.default_rng()
        for j in range(8):
            velocity = rng.uniform([-1, -1, 0], [1, 1, 0])
            material = kb.PrincipledBSDFMaterial(color=kb.random_hue_color(rng=rng))
            sphere = kb.Sphere(scale=0.1, velocity=velocity, material=material)
            scene += sphere
            kb.move_until_no_overlap(sphere, simulator, spawn_region=spawn_region)
        # --- executes the simulation (and store keyframes)
        simulator.run()
        # --- renders the output
        renderer.save_state("output/multiple_scene_"+str(i)+"/simulator.blend")
        kb.done()

 
I will appreciate very much for your suggestions.

**Comment by SiegeLordEx** [comment]
This is caused by https://github.com/google-research/kubric/issues/208. The workaround is to manually delete and `gc.collect()` the simulator instance.

**Comment by HAWLYQ** [comment]
Thanks for your advice! It works by adding `gc.collect()` at the end of each iteration.
