### ISSUE TITLE
How to render rectangular images rather than square images using kubric?

### ISSUE THREAD

**Issue by ZhangCYG** [google-research/kubric#249]
When using Movi-E, we run movi_def_worker_local.py as what README said. But we want to generate images with 640 * 480 resolution, we input the resolution as: parser.set_defaults(save_state=False, frame_end=24, frame_rate=12, resolution=[640, 480])(at line 68).
We yielded the correct rgb results but the segmentation files seem wrong.
![image](https://user-images.githubusercontent.com/62829225/176144038-ce4f846b-43f9-4c96-80f2-ae3f652d4cbb.png)
The bugs are as belows.
We would appreciate it if anyone can give us some advice about rendering images with 640 * 480 (and any other rectangular) resolution.

**Comment by sam-motamed** [comment]
Hi, was this ever fixed?
