### ISSUE TITLE
Point Tracking Dataset/Code Release

### ISSUE THREAD

**Issue by wenhsuanchu** [google-research/kubric#253]
Hey! For the long range point tracking data, the repo only contains a very vague description of "For long-term point tracking we make use of the objects_coordinates annotation in the MOVi-E dataset, along with ground-truth positions of objects and camera to generate point-tracks." Would it be possible for the authors to release the code and data that is used for generating these point tracklets from movi-e?

Thanks!

**Comment by cdoersch** [comment]
PR #246 is the implementation I used for these experiments.  We're still in the process of reviewing it, but you should be able to merge and use it.

**Comment by shivanimall** [comment]
found this helpful for instructions: https://github.com/facebookresearch/co-tracker/issues/8
