### ISSUE TITLE
how to preprocess shapenet

### ISSUE THREAD

**Issue by heurainbow** [google-research/kubric#271]
I download the ShapeNetCore.v2.zip from https://shapenet.org/download/kubric with gs://kubric-unlisted/assets/ShapeNetCore.v2.json.
I guess this zip file should be preprocessed (kubricfy) before using in example/shapenet.py since it doesn't have a tar.gz structure nor a data.json (would trigger a assertation error).

I find the shapenet2kubric folder. But there is no readme to tell how to do it. Anyone has a clue? I think it's better to provide a dev docker image and a script to support this preprocessing.

**Comment by heurainbow** [comment]
#212         

TL;DR: it's already published and publicly available.

Sadly I couldn't paste the shapenet cloud bucket path directly, as you need to sign the agreement first.
Once you have it, you can browse the models one by one (no need to download the entire thing), or just
have kubric point to the asset source.

_Originally posted by @taiya in https://github.com/google-research/kubric/issues/212#issuecomment-1138598782_

How can I use the preprocessed shapenet models?

**Comment by taiya** [comment]
Sorry, I don't get notifications for issues.
Indeed, it's publicly available (took 1.5 years of CPU time to compute)

Use? look at `examples/shapenet.py`, once you replace the path with the one from the license agreement you should be able to iterate through the models, download objs and so on and so forth.
