### ISSUE TITLE
Provide list of maps from Godot Engine to compare with Kubric

### ISSUE THREAD

**Issue by fire** [google-research/kubric#275]
Do you standardize the maps you output from kubric?

I want to try rendering the same scene from both blender and godot engine to compare.

This is a novice question.

**Comment by Qwlouse** [comment]
Not sure what you mean by standardize, and also which maps? RGB? Depth? Flow?
There is some detail on the output format here for reference: https://github.com/google-research/kubric/tree/main/challenges/movi#annotations-and-format

**Comment by fire** [comment]
Thanks. I'll investigate.
