### ISSUE TITLE
How to not render cretain maps?

### ISSUE THREAD

**Issue by malfonsoarquimea** [google-research/kubric#276]
I want to accelerate the execution of a worker. Is there a way to disable the rendering of certain maps (like backward and forward flows)? I don't need them at all
Thanks!

**Comment by Qwlouse** [comment]
Yes: https://github.com/google-research/kubric/blob/main/kubric/renderer/blender.py#L241

**Comment by malfonsoarquimea** [comment]
> Yes: https://github.com/google-research/kubric/blob/main/kubric/renderer/blender.py#L241

Thanks very much!
