### ISSUE TITLE
Steps to move to Blender 3 LTS

### ISSUE THREAD

**Issue by fire** [google-research/kubric#283]
Blender 3 LTS 

https://www.blender.org/download/releases/3-3/

**Comment by lauweiquan** [comment]
Hello, I did not use dockers and I managed to build kubric with blender 3.4 in a anaconda environment so I'll just share what I did.

use anaconda to create an env with python 3.10 (my exact version is python 3.10.8; the other versions will have DLL load fail)
follow this: [](https://github.com/google-research/kubric/issues/100)
for blender installation steps in the github, just ignore that part and use "pip install bpy" (this should build bpy 3.4 which is my native blender version)
*bpy successfully installed*
continue following the instruction to install kubric
missing openexr, hence dl here: [](https://anaconda.org/conda-forge/openexr-python)
pip install pybullet

done! you can run the examples where the blender files will be exported to an output but I can't seem to run some of the challenges properly.

**Comment by fire** [comment]
Thanks I'll investigate. Probably want a new bug for the challenges.
