### ISSUE TITLE
Can shadows be disabled?

### ISSUE THREAD

**Issue by wangyuyy** [google-research/kubric#291]
Hi, thanks for your great work for 3D dataset generation! It brought a lot convenience for 3D vision research!
However, the official doc remains to be completed.
So I wonder whether the shadows can be disabled?

**Comment by rwn17** [comment]
Hi @wangyuyy I noticed you just completed this issue and I was wondering do you figure out how to disable the shadow? I tried something according to [here](https://github.com/google-research/kubric/blob/e291953c3604bb8f1817e1d0b062fa2362562613/challenges/multiview_matting/worker.py#L74-L77) but it doesn't work. Thanks in advance!

**Comment by rwn17** [comment]
> 

For the people interested, please refer to [discussion](https://github.com/google-research/kubric/discussions/277)
