### ISSUE TITLE
Point tracking: Request to add information on "whether it is a foreground object" to annotation

### ISSUE THREAD

**Issue by sinkers-lan** [google-research/kubric#314]
Hi, I'd like to express my gratitude for your outstanding work on this project!

I am currently working on training a model using the MOVi-F dataset for point tracking purposes. During this process, I've encountered a specific need: distinguishing between points originating from foreground objects and those from the background. 

Would it be possible to introduce a feature in the annotation process that generates a label indicating whether a track belongs to a foreground object? Your guidance on how this might be achieved, or any existing solutions you could point me towards, would be greatly appreciated. If possible, I would greatly appreciate your assistance in incorporating this feature into the project. 

I believe it would make a significant contribution to its functionality and utility for researchers like myself. Thank you very much for your time and consideration.

**Comment by cdoersch** [comment]
Sorry, we don't support specific feature requests for this reader.  However, it shouldn't be hard for you to add this yourself.  The reader processes different objects in order: https://github.com/google-research/kubric/blob/main/challenges/point_tracking/dataset.py#L615 is a loop over the different objects which tracks a set of points on each one.  The background is processed differently: https://github.com/google-research/kubric/blob/main/challenges/point_tracking/dataset.py#L638 .  So you can create an array parallel to chosen_points here: https://github.com/google-research/kubric/blob/main/challenges/point_tracking/dataset.py#L654 and here: https://github.com/google-research/kubric/blob/main/challenges/point_tracking/dataset.py#L665 which will be an indicator of whether the point belongs to background.  Then you just have to concatenate it into a single vector and return it from the reader.

Hope that helps.
