### ISSUE TITLE
Dataset Export

### ISSUE THREAD

**Issue by Qwlouse** [google-research/kubric#32]
Currently the script generates a set of numpy arrays for the images, masks, optical flow etc. as well as a dict with meta-data information.
This information has to be structured in a standardized format, aggregated and converted into a TF dataset.

Preliminary suggestion for the format of each batch:
* image `(B, T, H, W, 3) float32` RGB information in the interval [0, 1]
* segmentation_id `(B, T, H, W, 2) int32` object IDs per pixel
* segmentation_alpha `(B, T, H, W, 2) float32` in the interval [0, 1]
* optical_flow `(B, T, H, W, 2) float32` in the interval [-1, 1]
* camera_position `(B, T, 3)`
* camera_rotation `(B, T, 3)`
* objects
    - number `(B, ) int32`  : number of objects in this scene
    - global_position `(B, K, 3) float32` global (world) coordinates of the object center of mass
    - global_rotation `(B, K, 3)  float32` orientation of the object in global (world) coordinates
   - id `(B, K) int32`  object/shape IDs
   - ...

**Comment by taiya** [comment]
There is a TF dataset definition file for worker/{Klevr,Katr}.
