### ISSUE TITLE
ShapeNet preprocessing

### ISSUE THREAD

**Issue by Qwlouse** [google-research/kubric#33]
Script for preprocessing ShapeNet so that it can be used as an AssetSource

- [x] prepare a docker container that contains all dependencies for the task
- [x] prepare a Makefile to replicate all efforts in standalone

**Comment by taiya** [comment]
From @IssamLaradji
```
I have added the documentation and the instructions in the ShapeNet branch of Kubric:
1- Instructions: https://github.com/google-research/kubric/tree/shapenet/process_shapenet
2- Docker: https://github.com/google-research/kubric/blob/shapenet/process_shapenet/make_docker.sh
3- Example of an Asset: https://github.com/google-research/kubric/tree/shapenet/process_shapenet/example/587cee5495322f18cf1584c5b09d332

The compressed files that it generates for each asset has the .mtl, .obj, and also the .gltk files.
```

**Comment by taiya** [comment]
Downloading ETA ~10h (25GB):
`http://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v2.zip`

**Comment by taiya** [comment]
This is the obj2gltf converted model (binary gltf file):
[114b662c64caba81bb07f8c2248e54bc.glb.zip](https://github.com/google-research/kubric/files/6898187/114b662c64caba81bb07f8c2248e54bc.glb.zip)

**Comment by taiya** [comment]
Meanwhile, I worked on this script this evening:
[shapenet2kurbic/parallel_obj2gltf.py](https://github.com/google-research/kubric/pull/112/files/e6e3059edd8ddb1f8c15ea25afe9fe4d8a662db7..3d022bf9c690159e905f031c17a9d8a9ae94741b#diff-88bfccfb16127d59621aba512fab7250efa8a1acf492a766e73cee03e9d39c29)

Which has a nice "kick" even on my simple 6 core machine w/ 400+ models/second:
```
/workspaces/kubric/shapenet2kubric: python3.7 parallel_obj2gltf.py
 48%|█████████████████▋                   | 5671/11860 [00:34<00:15, 401.35it/s]
```

**Comment by taiya** [comment]
Breaking down this issue into a collection of issues (milestone) for better tracking of problems.
