### ISSUE TITLE
ArXiv One-Pager

### ISSUE THREAD

**Issue by Qwlouse** [google-research/kubric#39]
A very brief placeholder paper that can be cited when using Kubric.
[Private overleaf link](https://www.overleaf.com/project/60918cf5b801b4d3a0074c28)

- [x] describe infrastructure + design decisions
- [x] describe 3/4 datasets + baselines
- [ ] publish datasets in public place ([see request](https://github.com/google-research/kubric/issues/80))

**Comment by taiya** [comment]
Closing as we are well on track
