### ISSUE TITLE
Integrate pybullet→blender in worker.py

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#4]
Main design decision: how to import mesh. As URDF not directly supported by blender, and pybullet mesh export is experimental.

Blender side
```
blender → bpy.ops.import_scene.obj(filepath=path, axis_forward='Y', axis_up='Z')
```

PyBullet side (post import) [docs](http://dirkmittler.homeip.net/blend4web_ce/uranium/bullet/docs/pybullet_quickstartguide.pdf):
```
getVisualShapeData(..)
```

**Comment by Qwlouse** [comment]
A first version of this is done. Using two different filenames for the physics  simulation and for the visual rendering.
