### ISSUE TITLE
Configure python linter

### ISSUE THREAD

**Issue by Qwlouse** [google-research/kubric#48]
Currently the automatic linting only fails on syntax errors. 
It should be properly configured to (partially) enforce our style guidelines.

**Comment by taiya** [comment]
This is now in the source tree:
https://github.com/google-research/kubric/blob/main/.pylintrc

But should be (1) configured and (2) added to the pre-merge checks.

**Comment by taiya** [comment]
From the [google python style guide](https://google.github.io/styleguide/pyguide.html) it seems they now provide a pylintrc: https://google.github.io/styleguide/pylintrc

- [ ] double check this is what we use (minus the 80→100 characters line)
