### ISSUE TITLE
make_render gives an error for the -t option

### ISSUE THREAD

**Issue by Sarasra** [google-research/kubric#52]
Hi,

I am following the steps for running on GCP with my project and instance. 

make_kubruntu finished successfully. Following is the output of make_render local which resulted in an error:

```
[name]@instance-1:~/kubric/kubric$ ./make_render.sh local
++ date +%b%d_%H%M%S
+ JOB_NAME=kubric_Aug20_144910
++ gcloud config get-value project
+ PROJECT_ID=[name]:[name]
+ TAG=gcr.io/[name]:[name]/kubric
+ REGION=us-central1
+ cat
+ docker build -f /tmp/Dockerfile -t gcr.io/[name]:[name]/kubric /home/[name]/kubric/kubric
invalid argument "gcr.io/[name]:[name]/kubric" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
+ cat
+ run_mode=local
+ shift
+ '[' local == local ']'
+ docker run gcr.io/[name]:[name]/kubric -- --output kubric_Aug20_144910/frame_
docker: invalid reference format.
See 'docker run --help'.
```

My guess: the issue is with my project id having a ':' in it. Any idea how to fix it?

(I retracted the names into [name])

**Comment by taiya** [comment]
yes, I think the shell script is being confused by characters like "[" and ":"

**Comment by Sarasra** [comment]
the project_id is something like google:capsule (there is no [ in it). Is there anyway to fix this or should we add a caution note about the project_id in readme?

**Comment by taiya** [comment]
Is the : something you added yourself or was it forced on you during project creation?
Not sure if you need to escape it `\:`

**Comment by Qwlouse** [comment]
Agreed, the most likely suspect is some unescaped character in the project_id. I would first try to add quotes around the TAG (and maybe also PWD while we are at it). 
I.e. change like 23 to:
`docker build -f /tmp/Dockerfile -t "$TAG" "$PWD"`
and line 48 to:
`  docker run "$TAG" \`

**Comment by Qwlouse** [comment]
Closing, because this is related to the old workflow and probably not relevant anymore.
