### ISSUE TITLE
Add spherical world (URDF + placer)

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#6]

**Comment by Qwlouse** [comment]
The included KLEVR asset source contains a `"Sphereworld.tar.gz"` that should work for this purpose. 
Uses a set of prisms as (convex) collision shapes. Needs to be tested though.
![sphereworld](https://user-images.githubusercontent.com/1160920/89771260-532a8580-db00-11ea-9deb-74be027511dd.png)

**Comment by taiya** [comment]
See `worker/katr` (only half-dome available)
