### ISSUE TITLE
Exported RGBA has a full alpha channel even for empty scenes.

### ISSUE THREAD

**Issue by msajjadi-g** [google-research/kubric#61]
I am rendering scenes with a single object and no background. The rendered background is black in the RGB, but the alpha channel is 255 for all pixels.

**Comment by taiya** [comment]
Having a black yet solid background is a perfectly valid state.
(might be memory inefficient, but valid) (Klaus+Andrea)

**Comment by Qwlouse** [comment]
This is intended behaviour. Under certain conditions Blender will generate a (non-solid) alpha-mask.
