### ISSUE TITLE
Distribute pre-generated datasets

### ISSUE THREAD

**Issue by vadimkantorov** [google-research/kubric#80]
It would be very helpful if Kubric put online some example datasets that Kubric's able to produce. This would allow getting familiar with the file structure (even if Kubric requires some polishing and is not ready for mass usage yet)

Another question: how much compute does dataset generation require? How long does it take? If it's hours of single-core cpu, it may be possible to just use GitHub Actions for generating simple CATER-like datasets.

**Comment by Qwlouse** [comment]
Perfectly timed question! I am currently writing some getting started docs + accompanying examples. Expect to see an update on this within a week. 

Compute requirements depend heavily on the desired resolution, quality, and complexity of the scene. But rendering a single frame like the one from the CATER dataset would probably take about a second on a single CPU. For 5500 videos with 240 frames each this would unfortunately already add up to about 2 weeks CPU time.  
But we will be hosting a few generated datasets soonish and plan to expand on this front as the project continues.

**Comment by vadimkantorov** [comment]
A parametrized GitHub action that renders and publishes a mini-dataset to GitHub releases would still be very nice to showcase different options (especially in academic environment where getting root/docker permissions takes quite some time or is impossible. if kubric gets packaged for conda, it's another story) and would allow the user to fork kubric and experiment with rendering options and maybe even generate a small dataset versions (e.g. 50 videos of 100 frames each).

Thanks!

**Comment by taiya** [comment]
Merged with the issue for the arXiv paper.
