### ISSUE TITLE
Typo for @add_asset.register(core.Sphere)

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#87]
Did you mean to write core.Sphere here?

https://github.com/google-research/kubric/blob/00697d0666780d51a1b9259709d56ca297443339/kubric/simulator/pybullet.py#L89
https://github.com/google-research/kubric/blob/00697d0666780d51a1b9259709d56ca297443339/kubric/simulator/pybullet.py#L90

**Comment by Qwlouse** [comment]
Yes indeed.

**Comment by Qwlouse** [comment]
fixed by #109
