### ISSUE TITLE
Readthedocs authentication?

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#94]
Hey Klaus, w.r.t. [this](https://readthedocs.org/accounts/login), can you:
1. add/share secrets to go/valentine
2. add auth to github secrets 
3. paste here a quick "how to upload docs"

**Comment by Qwlouse** [comment]
I created a `kubricrtd` user on readthedocs.org, added him as a maintainer to the kubric project, and shared the secret with you on go/valentine.
Do we need the auth in the github secrets?

Docs should upload automatically via the RTD webhook.

https://github.com/google-research/kubric/settings/hooks/276374996

AFAICT this does work, eventhough RTD is complaining on the project page that the webhook is not configured properly. No idea why.
