### ISSUE TITLE
Executing from Blender REPL (macOS)

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#99]
Install blender and make an alias to the contained python:
```
alias blender="/Applications/Blender.app/Contents/MacOS/Blender"
alias bython3="/Applications/Blender.app/Contents/Resources/2.91/python/bin/python3.7m"
```

Install the python headers (needed by mathutils and pybullet):
```
brew install python@3.7
HEADERS=/usr/local/Cellar/python@3.7/3.7.10_3/Frameworks/Python.framework/Headers
```

Install a (slightly stale) version of openexr:
```
brew install openexr@2  #< WARNING: do not install openexr3!
brew link openexr@2
ln -s /usr/local/opt/openexr\@2 /usr/local/opt/openexr
```

Install the python dependencies (and a symlinked version of kubric):
```
bython3 -m ensurepip
bython3 -m pip install --upgrade pip wheel
bython3 -m pip install --upgrade --global-option=build_ext --global-option=-I$HEADERS mathutils
bython3 -m pip install --upgrade --global-option=build_ext --global-option=-I$HEADERS pybullet
bython3 -m pip install --upgrade -r requirements.txt
```

Finally, you can execute as:
```
~/dev/kubric: blender --background --python examples/helloworld.py
Blender 2.91.2 (hash 5be9ef417703 built 2021-01-19 16:25:27)
Read prefs: /Users/atagliasacchi/Library/Application Support/Blender/2.91/config/userpref.blend
found bundled python: /Applications/Blender.app/Contents/Resources/2.91/python
pybullet build time: May 15 2021 15:41:49

Blender quit
Error: Not freed memory blocks: 1, total unfreed memory 0.001259 MB
```

This will generate a `helloworld.blend` and `helloworld.png` in the kubric folder:
![image](https://user-images.githubusercontent.com/4480573/118380779-54aa4200-b599-11eb-96c5-f4db7fc8dd85.png)

**Comment by baixianger** [comment]
> Install blender and make an alias to the contained python:
> 
> ```
> alias blender="/Applications/Blender.app/Contents/MacOS/Blender"
> alias bython3="/Applications/Blender.app/Contents/Resources/2.91/python/bin/python3.7m"
> ```
> 
> Install the python headers (needed by mathutils and pybullet):
> 
> ```
> brew install python@3.7
> HEADERS=/usr/local/Cellar/python@3.7/3.7.10_3/Frameworks/Python.framework/Headers
> ```
> 
> Install a (slightly stale) version of openexr:
> 
> ```
> brew install openexr@2  #< WARNING: do not install openexr3!
> brew link openexr@2
> ln -s /usr/local/opt/openexr\@2 /usr/local/opt/openexr
> ```
> 
> Install the python dependencies (and a symlinked version of kubric):
> 
> ```
> bython3 -m ensurepip
> bython3 -m pip install --upgrade pip wheel
> bython3 -m pip install --upgrade --global-option=build_ext --global-option=-I$HEADERS mathutils
> bython3 -m pip install --upgrade --global-option=build_ext --global-option=-I$HEADERS pybullet
> bython3 -m pip install --upgrade -r requirements.txt
> ```
> 
> Finally, you can execute as:
> 
> ```
> ~/dev/kubric: blender --background --python examples/helloworld.py
> Blender 2.91.2 (hash 5be9ef417703 built 2021-01-19 16:25:27)
> Read prefs: /Users/atagliasacchi/Library/Application Support/Blender/2.91/config/userpref.blend
> found bundled python: /Applications/Blender.app/Contents/Resources/2.91/python
> pybullet build time: May 15 2021 15:41:49
> 
> Blender quit
> Error: Not freed memory blocks: 1, total unfreed memory 0.001259 MB
> ```
> 
> This will generate a `helloworld.blend` and `helloworld.png` in the kubric folder: ![image](https://user-images.githubusercontent.com/4480573/118380779-54aa4200-b599-11eb-96c5-f4db7fc8dd85.png)

That would be a major help!!!!
